all:
	@javac Util/NodeInterface.java
	@javac Util/RBNodeInterface.java
	@javac Trie/Person.java
	@javac Trie/TrieNode.java
	@javac Trie/TrieInterface.java
	@javac Trie/Trie.java
	@javac Trie/TrieDriverCode.java
	@java Trie/TrieDriverCode Trie/input
	@javac RedBlack/RedBlackNode.java
	@javac RedBlack/RBTreeInterface.java
	@javac RedBlack/RBTree.java
	@javac RedBlack/RedBlackDriverCode.java
	@java RedBlack/RedBlackDriverCode RedBlack/input
	@javac PriorityQueue/Student.java
	@javac PriorityQueue/Node.java
	@javac PriorityQueue/PriorityQueueInterface.java
	@javac PriorityQueue/MaxHeap.java
	@javac PriorityQueue/PriorityQueueDriverCode.java
	@java PriorityQueue/PriorityQueueDriverCode PriorityQueue/input
	@javac ProjectManagement/SchedulerInterface.java
	@javac ProjectManagement/User.java
	@javac ProjectManagement/Project.java
	@javac ProjectManagement/Job.java
	@javac ProjectManagement/Scheduler_Driver.java
	@java ProjectManagement/Scheduler_Driver ProjectManagement/input
	@rm Util/*.class
	@rm Trie/*.class
	@rm RedBlack/*.class
	@rm PriorityQueue/*.class
	@rm ProjectManagement/*.class

